export const ranksMap = new Map()
ranksMap.set("master", 'orange')
ranksMap.set("newbie", 'gray')
ranksMap.set("candidate master", '#a0a')
ranksMap.set("legendary grandmaster", 'red')
ranksMap.set("grandmaster", 'red')
ranksMap.set("international grandmaster", 'red')
ranksMap.set("expert", 'blue')
ranksMap.set("specialist", '#03A89E')
ranksMap.set("pupil", 'green')